import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { IncompleteSquare } from "@/components/incomplete-square";
import { DotSquare } from "@/components/dot-square";

const firaCode = Fira_Code({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${firaCode.className} antialiased relative flex flex-col items-center gap-80`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <IncompleteSquare missingSide="r" className="top-[60vh] right-0" />
          <IncompleteSquare
            missingSide="r"
            className="top-[120vh] right-0 h-30 w-[60px]"
          />
          <DotSquare className="top-[340vh] right-0" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
